set_location_assignment PIN_Y23 -to x3
set_location_assignment PIN_Y24 -to x2
set_location_assignment PIN_AA22 -to x1
set_location_assignment PIN_AA23 -to x0
set_location_assignment PIN_AD27 -to y3
set_location_assignment PIN_AC27 -to y2
set_location_assignment PIN_AC28 -to y1
set_location_assignment PIN_AB28 -to y0
set_location_assignment PIN_H21 -to cp
set_location_assignment PIN_E24 -to s3
set_location_assignment PIN_E25 -to s2
set_location_assignment PIN_E22 -to s1
set_location_assignment PIN_E21 -to s0
set_location_assignment PIN_AB27 -to mode